[mgr]
ratio = [1, 3, 3]
linemode = "size"

[preview]
wrap = "yes"

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
group = "file"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
group = "dir"
run = "git"
